# Site settings
title: "Stanley McCatty"
email: "stanleymccatty@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  Stanley McCatty is a Brooklyn based web developer, and an all around schwifty person.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://notemakoti.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: "NoteMakoti"

# Build settings
markdown: redcarpet
